[build]
# Only install Python deps during build. Do NOT install browsers here.
buildCommand = "pip install -r requirements.txt"

[start]
# At container start: fetch Chromium, then run Gunicorn. Higher timeout for Playwright work.
startCommand = "bash start.sh && gunicorn -w 1 --timeout 180 -b 0.0.0.0:$PORT server:app"
