# railway.toml
[build]
builder = "dockerfile"

[deploy]
# Bind to the dynamic $PORT that Railway injects (so Cloudflare can proxy on 443)
# Using bash -lc ensures $PORT is expanded even if Railway execs directly.
startCommand = "bash -lc 'gunicorn --bind 0.0.0.0:${PORT} --timeout 120 --workers 2 server:app'"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
