[build]
# Only install Python deps at build
buildCommand = "pip install -r requirements.txt"

[start]
# Install Chromium into a writable path, then boot gunicorn
startCommand = "bash -lc 'export PLAYWRIGHT_BROWSERS_PATH=/app/ms-playwright && mkdir -p $PLAYWRIGHT_BROWSERS_PATH && python -m playwright install chromium && gunicorn -w 1 --timeout 180 -b 0.0.0.0:$PORT main:app'"
