[build]
# Install Python dependencies and Playwright browsers during build phase
buildCommand = "mkdir -p /tmp/ms-playwright && pip install -r requirements.txt && python -m playwright install --with-deps chromium"

[start]
# Start Gunicorn with sufficient timeout for Playwright operations
startCommand = "gunicorn -w 1 --timeout 180 -b 0.0.0.0:$PORT server:app"
